- name: install docker
  apt:
    name: docker.io
    state: latest

- name: docker ali mirror
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: restart docker
  systemd:
    name: docker
    state: restarted
    enabled: yes
