- name: update all packages to latest
  apt:
    upgrade: dist

- name: install base software
  apt:
    name:
      - curl
      - wget
      - vim
      - python3
      - python3-pip
      - tldr
      - nload
      - htop
      - jq
      - openssl
      - git
      - unzip
    state: latest

- name: python link to python3
  file:
    src: /usr/bin/python3
    path: /usr/bin/python
    state: link
  
- name: pip link to pip3
  file:
    src: /usr/bin/pip3
    path: /usr/bin/pip
    state: link

- name: 配置git editor为vim
  shell: git config --global core.editor vim

- name: 配置git user
  shell: git config --global user.name "guojiank"

- name: 配置git email
  shell: git config --global user.email "guojian_k@qq.com"

  