- name: update all packages to latest
  apt:
    upgrade: dist

- name: install base software
  apt:
    name:
      - curl
      - wget
      - vim
      - python3
      - python3-pip
      - tldr
      - nload
      - htop
      - jq
      - openssl
    state: latest


